version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.node
    networks:
      - backend
      - net_proxy
    depends_on:
      - db
    restart: always

  proxy:
    container_name: proxy
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:80
    networks:
      - net_proxy
    depends_on:
      - app
    restart: always

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - .docker:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
  net_proxy:
    name: net_proxy
    driver: bridge
